Repository Kim-jeongmin/ShoutOut-Android, pull requests merged in 2020-06, with the labels that each got.

#14 User information pr
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kimmessicorp/InformationActivity.java
  app/src/main/java/com/example/kimmessicorp/LoginActivity.java
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
  app/src/main/res/layout/activity_drawer.xml
  app/src/main/res/layout/activity_information.xml
  report.md
Labels: enhancement

#20 Parsing listviewdata
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
Labels: enhancement, help wanted

#24 View activity infor
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
  app/src/main/java/com/example/kimmessicorp/RegisterActivity.java
  app/src/main/java/com/example/kimmessicorp/ViewActivity.java
  app/src/main/java/com/example/kimmessicorp/viewRequest.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#27 Design2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kimmessicorp/InformationActivity.java
  app/src/main/java/com/example/kimmessicorp/LoginActivity.java
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
  app/src/main/java/com/example/kimmessicorp/RegisterActivity.java
  app/src/main/java/com/example/kimmessicorp/ViewActivity.java
  app/src/main/java/com/example/kimmessicorp/WriteActivity.java
  app/src/main/res/drawable-v24/ii.png
  app/src/main/res/drawable-v24/login.png
  app/src/main/res/drawable-v24/refresh.png
  app/src/main/res/drawable-v24/send.png
  app/src/main/res/drawable-v24/shout.png
  app/src/main/res/drawable-v24/upload.png
  app/src/main/res/layout/activity_drawer.xml
  app/src/main/res/layout/activity_information.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_view.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#28 새로고침 기능 구현
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
Labels: enhancement

#31 회원가입시 중복 확인 기능 구현
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
  app/src/main/java/com/example/kimmessicorp/RegisterActivity.java
  app/src/main/java/com/example/kimmessicorp/overlapRequest.java
  app/src/main/res/layout/activity_register.xml
Labels: enhancement

#35 bug fixed
  app/src/main/java/com/example/kimmessicorp/WriteActivity.java
Labels: bug

#36 Bug/refresh
  app/src/main/java/com/example/kimmessicorp/MainActivity.java
  app/src/main/java/com/example/kimmessicorp/WriteActivity.java
Labels: bug
